import { library } from '@fortawesome/fontawesome-svg-core';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';
import { 
    faPlus,
    faPencil,
    faTrash,
    faSort,
    faSortUp,
    faSortDown,
    faWindowRestore,
    faMicrochip,
    faProjectDiagram,
    faNetworkWired,
    faArrowLeft,
    faArrowRight,
    faBuilding,
    faDesktop,
    faDatabase,
    faCode,
    faTools,
    faExchangeAlt,
    faPlug,
    faCloud,
    faCube,
    faLayerGroup,
    faHome,
    faBars,
    faInfoCircle,
    faCog,
    faTimes,
    faTimesCircle,
    faSitemap,
    faBezierCurve,
    faEdit,
    faCrosshairs,
    faRefresh,
    faSave,
    faSpinner,
    faExternalLinkAlt
} from '@fortawesome/free-solid-svg-icons';

// Add icons to the library
library.add(
    faPlus,
    faPencil,
    faTrash,
    faSort,
    faSortUp,
    faSortDown,
    faWindowRestore,
    faMicrochip,
    faProjectDiagram,
    faNetworkWired,
    faArrowLeft,
    faArrowRight,
    faBuilding,
    faDesktop,
    faDatabase,
    faCode,
    faTools,
    faExchangeAlt,
    faPlug,
    faCloud,
    faCube,
    faLayerGroup,
    faHome,
    faBars,
    faInfoCircle,
    faCog,
    faTimes,
    faTimesCircle,
    faSitemap,
    faBezierCurve,
    faEdit,
    faCrosshairs,
    faRefresh,
    faSave,
    faSpinner,
    faExternalLinkAlt
);

export { FontAwesomeIcon }; 