import { library } from '@fortawesome/fontawesome-svg-core';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';
import { 
    faPlus,
    faPencil,
    faTrash,
    faWindowRestore,
    faMicrochip,
    faProjectDiagram,
    faNetworkWired,
    faArrowLeft,
    faArrowRight,
    faBuilding,
    faDesktop,
    faDatabase,
    faCode,
    faTools,
    faExchangeAlt,
    faPlug,
    faCloud,
    faCube,
    faLayerGroup,
    faHome,
    faBars,
    faInfoCircle,
    faCircleInfo,
    faTimes,
    faSitemap,
    faBezierCurve,
    faEdit,
    faCrosshairs,
    faRefresh,
    faFileContract,
    faCalendarAlt,
    faDollarSign,
    faCoins,
    faCopy,
    faExclamationTriangle,
    faExclamationCircle,
} from '@fortawesome/free-solid-svg-icons';

// Add icons to the library
library.add(
    faPlus,
    faPencil,
    faTrash,
    faWindowRestore,
    faMicrochip,
    faProjectDiagram,
    faNetworkWired,
    faArrowLeft,
    faArrowRight,
    faBuilding,
    faDesktop,
    faDatabase,
    faCode,
    faTools,
    faExchangeAlt,
    faPlug,
    faCloud,
    faCube,
    faLayerGroup,
    faHome,
    faBars,
    faInfoCircle,
    faCircleInfo,
    faTimes,
    faSitemap,
    faBezierCurve,
    faEdit,
    faCrosshairs,
    faRefresh,
    faFileContract,
    faCalendarAlt,
    faDollarSign,
    faCoins,
    faCopy,
    faExclamationTriangle,
    faExclamationCircle,
);

export { FontAwesomeIcon }; 